### ISSUE TITLE
[Problem]: OpenTTF stops opening font after 30 seconds.

### ISSUE THREAD

**Issue by Max-Rodriguez** [simple2d/simple2d#129]
My program crashes after some seconds as OpenTTF is unable to open a font, after already opening it perfectly for 30 seconds straight. I believe its because i'm declaring my text in render which continuously updates.

Im trying to make it not update every frame by defining my text and font before the `render()` function.

This is my attempt to fix the issue:

Header:
```c
S2D_Text *play;
void initialize();
void render();
void update();
```
Main:
```c
int main() {
  // Initialize Window
  S2D_Window *window = S2D_CreateWindow(
    "C-Pong", WIN_WIDTH, WIN_HEIGHT,
    update, render, 0
  );

  // Window Properties
  window -> fps_cap = FPS_MAX;
  window -> vsync = VSYNC;
  window -> icon = "res/icon.png";
  window -> on_key = input;

  initialize();
  S2D_Show(window);
  S2D_Close(window);
  S2D_FreeWindow(window);
  return EXIT_SUCCESS;
}

void initialize() {
  play = S2D_CreateText(
    "font", "text", 10
  );
}

void render() {
  play -> color.r = 1.0
  play -> color.g = 1.0
  play -> color.b = 1.0
  play -> color.a = 1.0
}

void update() {
  // A switch for flashing text, runs:
  S2D_DrawText(play);
  /* and */ S2D_FreeText(play);
}
```
But this gives me a segmentation fault....
**Why** is this giving me a segmentation fault?

**Comment by blacktm** [comment]
Hi @Max-Rodriguez, yes, the `update()` function gets called 60 times a second. If you move `S2D_FreeText(play);` out of the loop, should fix it (I hope).

**Comment by Max-Rodriguez** [comment]
> Hi @Max-Rodriguez, yes, the `update()` function gets called 60 times a second. If you move `S2D_FreeText(play);` out of the loop, should fix it (I hope).

The problem still exists. It exits with the same errors, after removing the `S2D_FreeText()`.

Note: I was using free text instead of changing the alpha since I get a segmentation fault when trying to access anything defined in render, even if the `S2D_Text` struct is defined globally.

I am forced to use `S2D_DrawText()` to render everything, so that's not the problem.
I believe the problem is that it's redefining the font, text, and size with `S2D_CreateText()` every frame on `update()`.

If I try to initialize a `S2D_Text` struct with `S2D_CreateText()` on another scope, while already globally declaring all my text structs, it will give me a seg fault if I try to access its properties from `update()`, so i'm forced to define it over and over inside the `update()` loop.

This is my take on what I think the issue is, but I may be wrong.

**Comment by Max-Rodriguez** [comment]
I just finished my Pong game using the Simple2D library.
It can be run perfectly fine but it still has the same issue if ran for longer than 30 seconds or so.

[](https://github.com/Max-Rodriguez/C-Pong)

**Comment by Max-Rodriguez** [comment]
I have an update on the issue:

When I run my game out of VSCode bash terminal window, it runs for 4 seconds.
though if I run it the same way from the integrated terminal, it runs for 20+ seconds.

Hope this helps with troubleshooting the issue ^
